<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;

/**
 * Class CreateUserProvidersTable
 *
 * Generated by ViKon\DbExporter
 */
class CreateUserProvidersTable extends Migration {
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up() {
        Schema::create('user_providers', function(Blueprint $table) {
            $table->increments('id')
                  ->unsigned();
            $table->integer('user_id')
                  ->unsigned();
            $table->string('provider', 255);
            $table->string('provider_id', 255);
            $table->string('avatar', 255)
                  ->nullable()
                  ->default(NULL);
            $table->timestamps();
            $table->softDeletes();
            $table->index('user_id', 'user_providers_user_id_foreign');
            $table->foreign('user_id', 'user_providers_user_id_foreign')
                  ->references('id')
                  ->on('users');
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down() {
        Schema::dropIfExists('user_providers');
    }
}