<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;

/**
 * Class CreateUsersTable
 *
 * Generated by ViKon\DbExporter
 */
class CreateUsersTable extends Migration {
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up() {
        Schema::create('users', function(Blueprint $table) {
            $table->increments('id')
                  ->unsigned();
            $table->string('avatar', 255);
            $table->string('name', 255);
            $table->string('email', 255);
            $table->string('password', 60)
                  ->nullable()
                  ->default(NULL);
            $table->boolean('status')
                  ->default('1');
            $table->string('confirmation_code', 255);
            $table->boolean('confirmed');
            $table->integer('org_id')
                  ->unsigned()
                  ->nullable()
                  ->default(NULL);
            $table->integer('role_id')
                  ->unsigned()
                  ->nullable()
                  ->default(NULL);
            $table->rememberToken();
            $table->timestamps();
            $table->softDeletes();
            $table->unique('email', 'users_email_unique');
            $table->index('org_id', 'users_org_id_foreign');
                       $table->foreign('org_id', 'users_org_id_foreign')
                  ->references('id')
                  ->on('organizations');
           $table->foreign('role_id')
                  ->references('id')
                  ->on('roles');
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down() {
        Schema::table('users', function(Blueprint $table){
            $table->dropForeign('users_org_id_foreign');
            //$table->dropForeign('users_role_id_foreign');
        });
        Schema::dropIfExists('users');
    }
}