<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;

/**
 * Class CreatePermissionsTable
 *
 * Generated by ViKon\DbExporter
 */
class CreatePermissionsTable extends Migration {
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up() {
        Schema::create('permissions', function(Blueprint $table) {
            $table->increments('id')
                  ->unsigned();
            $table->string('name', 255);
            $table->string('display_name', 255);
            $table->boolean('system');
            $table->timestamps();
            $table->unique('name', 'permissions_name_unique');
           
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down() {
        Schema::dropIfExists('permissions');
    }
}