<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;

/**
 * Class CreateLocationsTable
 *
 * Generated by ViKon\DbExporter
 */
class CreateLocationsTable extends Migration {
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up() {
        Schema::create('locations', function(Blueprint $table) {
            $table->increments('id')
                  ->unsigned();
            $table->integer('parent_id')
                  ->nullable()
                  ->default(NULL);
            $table->integer('lft')
                  ->nullable()
                  ->default(NULL);
            $table->integer('rgt')
                  ->nullable()
                  ->default(NULL);
            $table->integer('depth')
                  ->nullable()
                  ->default(NULL);
            $table->string('name', 255)->index()
                  ->nullable()
                  ->default(NULL);
            $table->string('type', 255);
            $table->string('pcode', 255)->unique();
            $table->string('alt_name', 255)->index()
                  ->nullable()
                  ->default(NULL);
            $table->string('mya_name', 255)->index()
                  ->nullable()
                  ->default(NULL);
            $table->string('alt_mya_name', 255)->index()
                  ->nullable()
                  ->default(NULL);
            $table->float('lon')
                  ->nullable()
                  ->default(NULL);
            $table->float('lat')
                  ->nullable()
                  ->default(NULL);
            $table->timestamps();
            $table->index('parent_id', 'locations_parent_id_index');
            $table->index('lft', 'locations_lft_index');
            $table->index('rgt', 'locations_rgt_index');

        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down() {
        Schema::drop('locations');
    }
}