<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;

/**
 * Class CreatePermissionUserTable
 *
 * Generated by ViKon\DbExporter
 */
class CreatePermissionUserTable extends Migration {
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up() {
        Schema::create('permission_user', function(Blueprint $table) {
            $table->increments('id')
                  ->unsigned();
            $table->integer('permission_id')
                  ->unsigned();
            $table->integer('user_id')
                  ->unsigned();
            $table->index('permission_id', 'permission_user_permission_id_foreign');
            $table->index('user_id', 'permission_user_user_id_foreign');
            $table->foreign('user_id', 'permission_user_user_id_foreign')
                  ->references('id')
                  ->on('users');

            $table->foreign('permission_id', 'permission_user_permission_id_foreign')
                  ->references('id')
                  ->on('permissions');
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down() {
        Schema::dropIfExists('permission_user');
    }
}