<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;

/**
 * Class CreateMediaTable
 *
 * Generated by ViKon\DbExporter
 */
class CreateMediaTable extends Migration {
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up() {
        Schema::create('media', function(Blueprint $table) {
            $table->increments('id')
                  ->unsigned();
            $table->string('filename', 255);
            $table->string('filedir', 255);
            $table->text('file');
            $table->integer('owner_id')
                  ->unsigned();
            $table->boolean('status');
            $table->timestamps();
            $table->softDeletes();
            $table->index('owner_id', 'media_owner_id_foreign');
                       $table->foreign('owner_id', 'media_owner_id_foreign')
                  ->references('id')
                  ->on('users');
                    });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down() {
        Schema::dropIfExists('media');
    }
}