<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;

/**
 * Class CreateQuestionsTable
 *
 * Generated by ViKon\DbExporter
 */
class CreateQuestionsTable extends Migration {
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up() {
        Schema::create('questions', function(Blueprint $table) {
            $table->increments('id')
                  ->unsigned();
            $table->integer('section')
                  ->nullable()
                  ->default(NULL);
            $table->integer('report')
                  ->nullable()
                  ->default(NULL);
            $table->string('qnum', 255)->index();
            $table->integer('sort');
            $table->text('question');
            $table->text('display');
            $table->text('related_data');
            $table->text('answers');
            $table->boolean('sameanswer');
            $table->string('answer_view', 255);
            $table->integer('related_id')
                  ->unsigned()
                  ->nullable()
                  ->default(NULL);
            $table->integer('project_id')
                  ->unsigned();
            $table->timestamps();
            $table->unique(['qnum', 'related_id', 'project_id'], 'questions_qnum_related_id_project_id_unique');
            $table->index('project_id', 'questions_project_id_foreign');
            $table->index('related_id', 'questions_related_id_foreign');
            $table->foreign('related_id', 'questions_related_id_foreign')
                  ->references('id')
                  ->on('questions');

            $table->foreign('project_id', 'questions_project_id_foreign')
                  ->references('id')
                  ->on('projects');
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down() {
        Schema::table('questions', function(Blueprint $table) {
            $table->dropForeign('questions_related_id_foreign');
            $table->dropForeign('questions_project_id_foreign');
        });
        Schema::dropIfExists('questions');
    }
}