<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;

/**
 * Class CreateProjectsTable
 *
 * Generated by ViKon\DbExporter
 */
class CreateProjectsTable extends Migration {
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up() {
        Schema::create('projects', function(Blueprint $table) {
            $table->increments('id')
                  ->unsigned();
            $table->string('name', 255)->index();
            $table->string('desc', 255)->index();
            $table->string('type', 255)->index();
            $table->integer('project_id')
                  ->unsigned()
                  ->nullable();
            $table->integer('org_id')
                  ->unsigned();
            $table->json('sections');
            $table->json('reporting');
            $table->string('validate');
            $table->string('urlhash');
            $table->timestamps();
            $table->unique('name', 'projects_name_unique');
            $table->index('project_id', 'projects_project_id_foreign');
            $table->index('org_id', 'projects_org_id_foreign');
            $table->foreign('org_id', 'projects_org_id_foreign')
                  ->references('id')
                  ->on('organizations');
            $table->foreign('project_id', 'projects_project_id_foreign')
                  ->references('id')
                  ->on('projects');
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down() {
        Schema::table('projects', function(Blueprint $table) {
            $table->dropForeign('projects_project_id_foreign');
            $table->dropForeign('projects_org_id_foreign');
        });
        Schema::dropIfExists('projects');
    }
}