<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;

/**
 * Class CreateOrganizationsTable
 *
 * Generated by ViKon\DbExporter
 */
class CreateOrganizationsTable extends Migration {
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up() {
        Schema::create('organizations', function(Blueprint $table) {
            $table->increments('id')
                  ->unsigned();
            $table->string('name', 255);
            $table->string('short', 255);
            $table->string('country', 255)->default('MM');
            $table->timestamps();
            $table->unique('name', 'organizations_name_unique');
           
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down() {
        Schema::dropIfExists('organizations');
    }
}