<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;

/**
 * Class CreatePcodeTable
 *
 * Generated by ViKon\DbExporter
 */
class CreatePcodeTable extends Migration {
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up() {
        Schema::create('pcode', function(Blueprint $table) {
            $table->string('primaryid')->unique()->index();
            $table->integer('org_id')->index()
                  ->unsigned()->nullable();
            $table->string('pcode', 255)->index();
            $table->string('uec_code', 255)->index();
            $table->integer('role_id')->unsigned()->nullable();
            $table->string('village')->nullable()->index();
            $table->string('village_tract')->nullable()->index();
            $table->string('township')->nullable()->index();
            $table->string('district')->nullable()->index();
            $table->string('state')->nullable()->index();
            $table->timestamps();
            $table->primary('primaryid');
            $table->foreign('org_id', 'pcode_org_id_foreign')
                  ->references('id')
                  ->on('organizations')
                  ->onUpdate('cascade')
                  ->onDelete('cascade');
        });
        
        Schema::table('participants', function(Blueprint $table){
            $table->foreign('pcode_id')
                  ->references('primaryid')
                  ->on('pcode');
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down() {
        Schema::table('participants', function(Blueprint $table){
            $table->dropForeign('participants_pcode_id_foreign');
        });
        Schema::drop('pcode');
    }
}