<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;

/**
 * Class CreateVersionsTable
 *
 * Generated by ViKon\DbExporter
 */
class CreateVersionsTable1 extends Migration {
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up() {
        Schema::create('versions', function(Blueprint $table) {
            $table->increments('version_id')
                  ->unsigned();
            $table->morphs('versionable');
            $table->integer('user_id')
                  ->nullable()
                  ->default(NULL);
            $table->binary('model_data');
            $table->string('reason', 100)
                  ->nullable()
                  ->default(NULL);
            $table->timestamps();
           
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down() {
        Schema::drop('versions');
    }
}