<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;

/**
 * Class CreateParticipantRolesTable
 *
 * Generated by ViKon\DbExporter
 */
class CreateParticipantRolesTable extends Migration {
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up() {
        Schema::create('participant_roles', function(Blueprint $table) {
            $table->increments('id')
                  ->unsigned();
            $table->string('name', 255);
            $table->string('level', 255);
            $table->timestamps();
            $table->unique(['name', 'level'], 'participant_roles_name_level_unique');

                    });
        Schema::table('participants', function(Blueprint $table){
            $table->foreign('role_id')
                  ->references('id')
                  ->on('participant_roles');
        });  
        Schema::table('pcode', function(Blueprint $table){
            $table->foreign('role_id')
                  ->references('id')
                  ->on('participant_roles');
        }); 
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down() {
        Schema::table('participants', function(Blueprint $table){
            $table->dropForeign('participants_role_id_foreign');
        });
        Schema::table('pcode', function(Blueprint $table){
            $table->dropForeign('pcode_role_id_foreign');
        });
        Schema::drop('participant_roles');
    }
}